// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Models.Entities;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250104062100_RenameExpenseDebitIdToTransactionId")]
    partial class RenameExpenseDebitIdToTransactionId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Entities.Expense", b =>
                {
                    b.Property<int>("DebitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("debit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DebitId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("DebitId")
                        .HasName("expense_pkey");

                    b.ToTable("expense", (string)null);
                });

            modelBuilder.Entity("Server.Models.Entities.Income", b =>
                {
                    b.Property<int>("CreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("credit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("CreditId")
                        .HasName("income_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("income", (string)null);
                });

            modelBuilder.Entity("Server.Models.Entities.Split", b =>
                {
                    b.Property<int>("SplitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("split_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SplitId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("transaction_id")
                        .HasColumnType("integer");

                    // b.Property<int>("TransactionId")
                    //     .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("SplitId")
                        .HasName("split_pkey");

                    b.HasIndex("transaction_id");

                    b.HasIndex("UserId");

                    b.ToTable("splits", (string)null);
                });

            modelBuilder.Entity("Server.Models.Entities.SplitParticipant", b =>
                {
                    b.Property<decimal>("Owes")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<bool?>("PaidStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("paid_status");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    b.Property<int>("SplitId")
                        .HasColumnType("integer")
                        .HasColumnName("split_id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SplitId");

                    b.ToTable("split_participants", (string)null);
                });

            modelBuilder.Entity("Server.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Server.Models.Entities.UserBalance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("balance");

                    b.HasKey("UserId")
                        .HasName("user_balance_pkey");

                    b.ToTable("user_balance", (string)null);
                });

            modelBuilder.Entity("Server.Models.Entities.Income", b =>
                {
                    b.HasOne("Server.Models.Entities.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Entities.Split", b =>
                {
                    b.HasOne("Server.Models.Entities.Expense", "Expense")
                        .WithMany()
                        .HasForeignKey("transaction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Entities.User", "User")
                        .WithMany("Splits")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_users");

                    b.Navigation("Expense");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Entities.SplitParticipant", b =>
                {
                    b.HasOne("Server.Models.Entities.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .IsRequired()
                        .HasConstraintName("fk_users");

                    b.HasOne("Server.Models.Entities.Split", "Split")
                        .WithMany()
                        .HasForeignKey("SplitId")
                        .IsRequired()
                        .HasConstraintName("fk_split");

                    b.Navigation("Participant");

                    b.Navigation("Split");
                });

            modelBuilder.Entity("Server.Models.Entities.UserBalance", b =>
                {
                    b.HasOne("Server.Models.Entities.User", "User")
                        .WithOne("UserBalance")
                        .HasForeignKey("Server.Models.Entities.UserBalance", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Entities.User", b =>
                {
                    b.Navigation("Incomes");

                    b.Navigation("Splits");

                    b.Navigation("UserBalance");
                });
#pragma warning restore 612, 618
        }
    }
}
